name: buypass_seller
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^15.1.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.12
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_image_compress: ^2.4.0
  permission_handler: ^12.0.0+1
  retrofit: ^4.4.2
  dio: ^5.8.0+1
  flutter_gen: ^5.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  cached_network_image: ^3.4.1
  flutter_gen_runner: ^5.10.0
  retrofit_generator: ^9.1.9



flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true